# Generated by Django 5.1.6 on 2025-04-27 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0031_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorreg',
            name='mobilenumber',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit mobile number', regex='^\\d{10}$')]),
        ),
    ]
