# Generated by Django 5.1.6 on 2025-04-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0030_alter_customuser_user_type_alter_page_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorreg',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
